spring.application.name=cloud-meta-storage

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/cloud_meta_storage
spring.datasource.username=postgres
spring.datasource.password=S@hil906q

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# JWT Configuration
app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
app.jwt.expiration=${JWT_EXPIRATION:86400000}